export const ingredients = [
  'Acciughe',
  'Aglio',
  'Ananas',
  'Basilico',
  'Brie',
  'Bresaola',
  'Capperi',
  'Carciofi',
  'Cipolla',
  'Crema di Tartufo',
  'Fontina',
  'Frutti di Mare',
  'Friarielli',
  'Funghi',
  'Funghi Porcini',
  'Gorgonzola',
  'Grana',
  'Limone',
  'Melanzane',
  'Mozzarella',
  'Mozzarella di Bufala',
  'Noci',
  "Olio d'oliva",
  'Olive',
  'Origano',
  'Pancetta',
  'Parmesan',
  'Patate',
  'Pepe',
  'Peperoni',
  'Pecorino',
  'Pollo',
  'Pomodoro',
  'Prezzemolo',
  'Prosciutto',
  'Rucola',
  'Rosmarino',
  'Sale',
  'Salame Piccante',
  'Salsiccia',
  'Speck',
  'Tonno',
  'Uovo',
  'Verdure Grigliate',
  'Zucchine'
]
