 
### Che mi dia tutte le pizze
GET https://pizza-api-htu2.onrender.com/api/pizza

### CREA UNA PIZZA NUOVA
POST https://pizza-api-htu2.onrender.com/api/pizza
Content-Type: application/json

{
    "name": "Ortolana",
    "price": 8,
    "cover": "/ortolana.webp",
    "ingredients": ["Pomodoro", "Mozzarella", "Melanzane", "Peperoni", "Zucchine"]
}

### Select User by mail and password
GET http://localhost:8080/user?email=1&password=1

### create User
POST http://localhost:8080/user/
Content-Type: application/json

{
    "name": "Menor113",
    "email": "klk113@gmail.com",
    "password": "80956010322"
}


### CREA UNA PIZZA NUOVA 
POST http://localhost:8080/pizza/
Content-Type: application/json

{
    "name": "Gamberi e Rucola",
    "price": 8,
    "cover": "/gamberierucola.webp",
    "ingredients": ["Pomodoro", "Mozzarella", "Gamberi", "Rucola"]
}

### all pizzas
GET http://localhost:8080/pizza/

### all pizza's name
GET http://localhost:8080/pizza/names/

### ID
GET http://localhost:8080/pizza/9e18050c-2658-11ef-9c4e-c1b133e9f926

### Name
GET http://localhost:8080/pizza?name=nAP


### Ingredients
GET http://localhost:8080/pizza?ingredients=Pe